version: '3'

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/lxu-wu/data/database
      type: volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/lxu-wu/data/wordpress
      type: volume
      o: bind


networks:
  my_network:


services:
  nginx:
    container_name: nginx
    image: img_nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - my_network
    build:
      context: ./requirements/nginx
    restart: unless-stopped
  
  wordpress:
    container_name: wordpress
    image: img_wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - my_network
    environment:
      - WP_URL=${WP_URL}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_DB=${MARIADB_DB}
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - my_network
    environment:
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
    restart: unless-stopped
